added error handling

diff --git a/ansiipythonium b/ansiipythonium
--- a/ansiipythonium
+++ b/ansiipythonium
@@ -6,6 +6,11 @@ if [ "$1" == "gen" ]; then
     java -jar $ANTLR -Dlanguage=Python3 -o output Ansiipythonium.g4
 elif [ "$1" == "run" ]; then
     python3 main.py "$2" | llc -o temp.s
+    if [ ! -f temp.s ]; then
+        echo "error occurred"
+        exit 1
+    fi
+
     clang -no-pie temp.s -o program
     rm temp.s
     ./program
